[ControlInputs]
case-name = "test-case"
grid-name = "test.grid"
iter-end = 1000
nx = 32
ny = 17
nz = 27
restart = true
write-interval = 1000

[NumericalInputs]
absolute-epsilone = 1e-14
machine-epsilone = 1e-16
relative-epsilone = 1e-15
cfl = 1.0
[NumericalInputs.Scheme]
epsilone = 0.4 # for roe's average
theta = 0.25 # for muscl minmod limiter

[ChemistryInputs]
# spcs used in calculation
thermo-table = "" # table file name
trans-table = "" # table name 
reaction-model = "jachimowski" # file name of reaction model input 

[FlowFieldInputs]
# same property for all flow fields
length-scale = 3.0 # as name meant
cdl = 1.0 # computation domain length x y z direction
ctk = -3.0 # coefficient for calculating initial turbulent viscosity coefficient
ctw = 5.0 #  coefficient for calculating initial specific turbulent kinetic energy disspation rate
#kappa = 1.01 # unknown

[FlowFieldInputs.Inflow] # allways read by library
mach = 4.0 # in flow mach number
pressure = 1e6 # inflow pressure [Pa], 1 bar
temp = 1200.0 # inflow temperature[K]
#mixture name
mixture-name = ["N2", "O2", "H2", "NO", "OH", "NO2", "HNO", "HO2", "H2O", "H2O2", "N", "O", "H"] 
# mixture mole for each species
mixture-value = [3.76d0 ,1.d0 ,2.d0 ,0.d0 ,0.d0 ,0.d0,0.d0,0.d0,0.d0,0.d0,0.d0,0.d0 ,0.d0]

# now read by user
